### ISSUE TITLE
Doesn't work when used in subdirectories

### ISSUE THREAD

**Issue by chenglou** [schreifels/git-num#4]
Output:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    new file:   [?] bla/0.jpg
```

**Comment by schreifels** [comment]
Thanks for the report, @chenglou ! This looks like an issue with how output from `git status --porcelain` is mapped to `git status`. I rewrote that implementation a while ago because of limitations like this. The new approach is much more robust (and behaves slightly differently, see [CHANGELOG.md](https://github.com/schreifels/git-num/blob/master/CHANGELOG.md#200-not-released)), but I have not cut a release for it yet. I intend to do this in the next few weeks, but the [code on master](https://github.com/schreifels/git-num/blob/master/git-num) should fix your issue. Let me know if this is not the case.

I will leave this issue open until I officially release v2.

**Comment by schreifels** [comment]
Done: https://github.com/schreifels/git-num/releases

**Comment by chenglou** [comment]
Woohoo! Thanks =D
